# Site settings
title: Martin Kersner
email: contact@martinkersner.com
url: //martinkersner.com

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#fff'
  links: '#219ab3'

# Footer settings
footer: 2020

# Team names, titles and social links
team_list:
  - martin

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
